// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyPgk91UFZqnxZzQ7pEkLnBY-xjf-qQHQ',
    appId: '1:274384716471:web:51111abc9fbf99cf788332',
    messagingSenderId: '274384716471',
    projectId: 'food-delivery-app-3c224',
    authDomain: 'food-delivery-app-3c224.firebaseapp.com',
    storageBucket: 'food-delivery-app-3c224.appspot.com',
    measurementId: 'G-5HV35N5Y51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQvskcu2MWA-GD2A764ICR3OFor1aL1XU',
    appId: '1:274384716471:android:1be565f16910faa9788332',
    messagingSenderId: '274384716471',
    projectId: 'food-delivery-app-3c224',
    storageBucket: 'food-delivery-app-3c224.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbVDtdIZIvO1uFexHMTV_7hQ9_rg9UWuM',
    appId: '1:274384716471:ios:8b9c68f484a0660a788332',
    messagingSenderId: '274384716471',
    projectId: 'food-delivery-app-3c224',
    storageBucket: 'food-delivery-app-3c224.appspot.com',
    iosClientId: '274384716471-vc0ip8psju4186cs710h2r660knfi4tk.apps.googleusercontent.com',
    iosBundleId: 'com.cmoyates.fooddeliveryapp',
  );
}
